#!/bin/sh
# Build and execute the upstream's testsuite for FreeImage against the
# installed binaries.

set -e

# Fetch the upstream testsuite.
cp -a TestAPI "$AUTOPKGTEST_TMP"

# Build using the installed FreeImagePlus package.
cd "$AUTOPKGTEST_TMP/TestAPI" && \
g++ *.cpp -lfreeimage -o test-freeimage && \
./test-freeimage
